services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_postgres
    networks:
      - ai_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai_web_app:
    image: ai_web_app
    container_name: ai_web_app
    networks:
      - ai_network
    ports:
      - "8080:5000"
    volumes:
      - .:/myapp
    depends_on:
      - postgres

  fastapi-app:
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  ai_network:

volumes:
  postgres_data: